//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HansPlcConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HansPlcConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired.
        /// </summary>
        public static string ___Acquired__ {
            get {
                return ResourceManager.GetString("___Acquired__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ___Description__ {
            get {
                return ResourceManager.GetString("___Description__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dew Point.
        /// </summary>
        public static string ___Dew_Point__ {
            get {
                return ResourceManager.GetString("___Dew_Point__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ___Height__ {
            get {
                return ResourceManager.GetString("___Height__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is as cold as it should be at the nort pole..
        /// </summary>
        public static string ___It_is_as_cold_as_it_should_be_at_the_nort_pole___ {
            get {
                return ResourceManager.GetString("___It_is_as_cold_as_it_should_be_at_the_nort_pole___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is as cold as it should be at the souht pole..
        /// </summary>
        public static string ___It_is_as_cold_as_it_should_be_at_the_souht_pole___ {
            get {
                return ResourceManager.GetString("___It_is_as_cold_as_it_should_be_at_the_souht_pole___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fairly warm at the north pole..
        /// </summary>
        public static string ___It_is_fairly_warm_at_the_north_pole___ {
            get {
                return ResourceManager.GetString("___It_is_fairly_warm_at_the_north_pole___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fairly warm at the south pole..
        /// </summary>
        public static string ___It_is_fairly_warm_at_the_south_pole___ {
            get {
                return ResourceManager.GetString("___It_is_fairly_warm_at_the_south_pole___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is freezing in Kriva..
        /// </summary>
        public static string ___It_is_freezing_in_Kriva___ {
            get {
                return ResourceManager.GetString("___It_is_freezing_in_Kriva___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is freezing in Verl..
        /// </summary>
        public static string ___It_is_freezing_in_Verl___ {
            get {
                return ResourceManager.GetString("___It_is_freezing_in_Verl___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not freezing in Kriva..
        /// </summary>
        public static string ___It_is_not_freezing_in_Kriva___ {
            get {
                return ResourceManager.GetString("___It_is_not_freezing_in_Kriva___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not freezing in Verl..
        /// </summary>
        public static string ___It_is_not_freezing_in_Verl___ {
            get {
                return ResourceManager.GetString("___It_is_not_freezing_in_Verl___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kriva, Slovakia.
        /// </summary>
        public static string ___Kriva__Slovakia__ {
            get {
                return ResourceManager.GetString("___Kriva__Slovakia__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kriva station is not available..
        /// </summary>
        public static string ___Kriva_station_is_not_available___ {
            get {
                return ResourceManager.GetString("___Kriva_station_is_not_available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string ___Length__ {
            get {
                return ResourceManager.GetString("___Length__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string ___Max__ {
            get {
                return ResourceManager.GetString("___Max__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string ___Min__ {
            get {
                return ResourceManager.GetString("___Min__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North pole station.
        /// </summary>
        public static string ___North_pole_station__ {
            get {
                return ResourceManager.GetString("___North_pole_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North pole station is not available..
        /// </summary>
        public static string ___North_pole_station_is_not_available___ {
            get {
                return ResourceManager.GetString("___North_pole_station_is_not_available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string ___Pressure__ {
            get {
                return ResourceManager.GetString("___Pressure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name.
        /// </summary>
        public static string ___Recipe_name__ {
            get {
                return ResourceManager.GetString("___Recipe_name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, the weather situation is following.
        /// </summary>
        public static string ___So__the_weather_situation_is_following__ {
            get {
                return ResourceManager.GetString("___So__the_weather_situation_is_following__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South pole station.
        /// </summary>
        public static string ___South_pole_station__ {
            get {
                return ResourceManager.GetString("___South_pole_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South pole station is not available..
        /// </summary>
        public static string ___South_pole_station_is_not_available___ {
            get {
                return ResourceManager.GetString("___South_pole_station_is_not_available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station name (ICAO).
        /// </summary>
        public static string ___Station_name__ICAO___ {
            get {
                return ResourceManager.GetString("___Station_name__ICAO___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station status.
        /// </summary>
        public static string ___Station_status__ {
            get {
                return ResourceManager.GetString("___Station_status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string ___Temperature__ {
            get {
                return ResourceManager.GetString("___Temperature__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string ___Thickness__ {
            get {
                return ResourceManager.GetString("___Thickness__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verl, Germany.
        /// </summary>
        public static string ___Verl__Germany__ {
            get {
                return ResourceManager.GetString("___Verl__Germany__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verl station is not available..
        /// </summary>
        public static string ___Verl_station_is_not_available___ {
            get {
                return ResourceManager.GetString("___Verl_station_is_not_available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string ___Visibility__ {
            get {
                return ResourceManager.GetString("___Visibility__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What plc says.
        /// </summary>
        public static string ___What_plc_says__ {
            get {
                return ResourceManager.GetString("___What_plc_says__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind heading.
        /// </summary>
        public static string ___Wind_heading__ {
            get {
                return ResourceManager.GetString("___Wind_heading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        public static string ___Wind_speed__ {
            get {
                return ResourceManager.GetString("___Wind_speed__", resourceCulture);
            }
        }
    }
}
